# Generated by Django 5.1.3 on 2025-01-25 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_order_user_delete_cartitem_delete_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
    ]
