# Generated by Django 5.1.3 on 2025-01-31 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_order_products_remove_order_user_review_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='name',
        ),
    ]
