# Generated by Django 5.1.3 on 2025-02-03 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_review_star'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='name',
        ),
    ]
