# Generated by Django 5.1.3 on 2025-02-04 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_rename_brand_product_brands_alter_brand_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='brands',
            new_name='brand',
        ),
    ]
