# Generated by Django 5.1.5 on 2025-02-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_remove_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ManyToManyField(to='product.brand'),
        ),
    ]
