# Generated by Django 5.1.3 on 2025-02-18 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
