# Generated by Django 5.1.3 on 2025-02-19 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='total_amount',
        ),
    ]
