# Generated by Django 5.1.3 on 2025-02-19 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_remove_cart_is_paid_remove_cart_total_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
