# Generated by Django 5.1.3 on 2025-02-21 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_delete_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='headphone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='headphone_reviews', to='product.headphone'),
        ),
        migrations.AddField(
            model_name='review',
            name='keybord',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='keybord_reviews', to='product.keybord'),
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='product.product'),
        ),
    ]
