# Generated by Django 5.1.3 on 2025-02-21 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_review_headphone_review_keybord_alter_review_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='headphone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='product.headphone'),
        ),
        migrations.AlterField(
            model_name='review',
            name='keybord',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='product.keybord'),
        ),
    ]
