# Generated by Django 5.1.7 on 2025-03-19 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0037_cart_added_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keybord',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.DeleteModel(
            name='Headphone',
        ),
        migrations.DeleteModel(
            name='Keybord',
        ),
    ]
